language: node_js

node_js:
  - "0.11"
  - "0.10"
  - "0.9"
  - "0.8"

before_script:
  - mysql -e "CREATE DATABASE `docMyDB`;"
  - mysql -e "CREATE TABLE IF NOT EXISTS `docMyDB`.`folder`(`id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ID.', `parentId` INT UNSIGNED NULL COMMENT 'Link to parent folder.', `name` VARCHAR(255) NOT NULL COMMENT 'Name of folder.', PRIMARY KEY (`id`, `parentId`), INDEX `FKFolderToFolder` (`parentId` ASC), CONSTRAINT `FKFolderToFolder` FOREIGN KEY (`parentId`) REFERENCES `docMyDB`.`folder` (`id`)  ON DELETE NO ACTION  ON UPDATE NO ACTION) ENGINE = InnoDB COMMENT = 'List of folders.';"